[build]
  command = "npm run build"
  publish = "out"
  base = "."

[build.environment]
  NODE_VERSION = "18"

# Redirects for SPA behavior
[[redirects]]
  from = "/projects/*"
  to = "/projects/:splat/index.html"
  status = 200

# This redirect is problematic for a multi-page Next.js static export.
# It will likely send all page requests to your site's root index.html.
# Consider removing it if you want users to access individual pages like /about, /contact, etc.
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# Headers for better performance
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"